image: rust:latest

stages:
    - build
    - deploy

build:
    stage: build
    before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    script:
        - bash build.sh
    artifacts:
        paths:
            - .public
    only:
        - master

pages:
    stage: deploy
    script:
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - master