[package]
name = "springbox"
version = "0.1.0"
authors = ["​ <>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"

[profile.release]
lto = true
opt-level = 3
